export const letters = [
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
  "M",
  "N",
  "O",
  "P",
  "Q",
  "R",
  "S",
  "T",
  "U",
  "V",
  "W",
  "X",
  "Y",
  "Z",
];

export const searchOptions = [
  { value: "ALL", label: "All" },
  { value: "Category", label: "Category" },
  { value: "Subcategory", label: "Subcategory" },
  { value: "Inner", label: "Inner" },
  { value: "Tags", label: "Tags" },
  { value: "Taggroup", label: "Tag Group" },
  { value: "Weathertag", label: "Weather Tag" },
  { value: "wellgorithms", label: "Wellgorithm" },
  { value: "Article", label: "Article" },
  { value: "Articleseries", label: "Article Series" },
];
